name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'  # Adjust the Python version

      - name: Install Streamlit dependencies
        run: |
          cd streamlit_app
          pip install -r requirements.txt

      - name: Deploy Streamlit app
        run: |
          cd streamlit_app
          streamlit run streamlit_app.py
